Add VaranSL; Brewer's Supplies
TheGiddyLimit/homebrew pull request #1077
Opened 2021-09-06 15:40 UTC by Lxran

For BREW-300

2021-09-06 16:04 UTC, revilowaldow requested changes
Missing Tag

2021-09-06 16:04 UTC, revilowaldow commented on variantrule/VaranSL; Brewer's Supplies.json
> +                      "Boulder Beer",
Should be `"{@optfeature Boulder Beer|BS}",`
i.e. missing tag

2021-09-06 16:24 UTC, revilowaldow approved these changes

2021-09-11 19:21 UTC, TheGiddyLimit approved these changes

2021-09-11 19:21 UTC, merged