Adding a new class brew and updating another class brew
TheGiddyLimit/homebrew pull request #1191
Opened 2022-01-03 10:07 UTC by Foxfire94

Adding my new "Vampire" class to the repo and some minor adjustments to the Astartes Initiate.

2022-01-04 16:59 UTC, revilowaldow requested changes
These three fixes should make it pass the schema.

2022-01-04 16:59 UTC, revilowaldow commented on class/Foxfire94; Vampire.json
> +									"exact": "24+"
This needs to be an integer.
`"exact": 24`

2022-01-04 16:59 UTC, revilowaldow commented on class/Foxfire94; Vampire.json
> +				"Choose one creature you can see within range that is in bright or dim light. That creature must make a Strength saving throw against your power save DC as inky black tendrils attempt to pull the
Lowercase v
`"v": true`

2022-01-04 16:59 UTC, revilowaldow commented on class/Foxfire94; Vampire.json
> +				"Choose one creature you can see within range that is in bright or dim light. That creature must make a Strength saving throw against your power save DC as inky black tendrils attempt to pull the
Lowercase v
`"v": true`

2022-01-04 17:06 UTC, revilowaldow commented on class/Foxfire94; Vampire.json
> +				"Choose one creature you can see within range that is in bright or dim light. That creature must make a Strength saving throw against your power save DC as inky black tendrils attempt to pull the
Not sure what happened here, should be line 9887

2022-01-04 17:06 UTC, revilowaldow commented on class/Foxfire94; Vampire.json
> +				"Choose one creature you can see within range that is in bright or dim light. That creature must make a Strength saving throw against your power save DC as inky black tendrils attempt to pull the
Not sure what happened here, should be line 9944

2022-01-07 00:08 UTC, TheGiddyLimit approved these changes

2022-01-07 00:09 UTC, merged