Patch 1
TheGiddyLimit/homebrew pull request #1211
Opened 2022-01-22 20:59 UTC by DarkJyka

2022-01-22 21:38 UTC, TheGiddyLimit requested changes

2022-01-22 21:38 UTC, TheGiddyLimit commented on collection/CheesiestMaster; Teyas's Guide to Aile.json
> +            "source": "http://potato.jdsnetwork.com/DnD/TGtA.json",
needs to be `"TeyasGuidetoAile"`

2022-01-22 21:38 UTC, TheGiddyLimit commented on collection/CheesiestMaster; Teyas's Guide to Aile.json
> +                "url": "https://github.com/TheGiddyLimit/homebrew",
you can/should put `""http://potato.jdsnetwork.com/DnD/TGtA.json"` here instead

2022-01-22 21:38 UTC, TheGiddyLimit commented on collection/CheesiestMaster; Teyas's Guide to Aile.json
> +            "tokenUrl": "https://5etools-mirror-1.github.io/img/MM/Swarm of Wasps.png?v=1.147.13",
drop the `?v=1.147.13` from the end--it isn't going to break anything, but it doesn't do anything either (besides maybe serving a stale version of the image from your cache)

2022-01-23 21:54 UTC, revilowaldow requested changes

2022-01-23 21:54 UTC, revilowaldow commented on collection/CheesiestMaster; Teyas's Guide to Aile.json
> +            "source": "http://potato.jdsnetwork.com/DnD/TGtA.json",
```suggestion
            "source": "TeyasGuidetoAile",
```

2022-01-23 21:54 UTC, revilowaldow commented on collection/CheesiestMaster; Teyas's Guide to Aile.json
> +                "url": "https://github.com/TheGiddyLimit/homebrew",
```suggestion
                "url": "http://potato.jdsnetwork.com/DnD/TGtA.json",
```

2022-01-23 21:54 UTC, revilowaldow commented on collection/CheesiestMaster; Teyas's Guide to Aile.json
> +            "tokenUrl": "https://5etools-mirror-1.github.io/img/MM/Swarm of Wasps.png?v=1.147.13",
```suggestion
            "tokenUrl": "https://5etools-mirror-1.github.io/img/MM/Swarm of Wasps.png",
```

2022-02-17 05:11 UTC, closed without merging