Added NotTheSmoooze; Roguish Archetypes
TheGiddyLimit/homebrew pull request #1223
Opened 2022-01-30 22:28 UTC by CorrTerek

I've added NotTheSmoooze's Roguish Archetypes. This is my first time submitting a pull request. I hope I have done so correctly.

2022-02-01 00:25 UTC, TheGiddyLimit approved these changes
Looks about right to me 👍

2022-02-01 00:30 UTC, TheGiddyLimit requested changes
I take it all back; the automated tests hadn't finished 🥴

2022-02-01 00:30 UTC, TheGiddyLimit commented on subclass/NotTheSmoooze; RoguishArchetypes.json
> +					"name": "Superstitions",
this shouldn't have a `name`/`source`/`page`

2022-02-01 00:30 UTC, TheGiddyLimit commented on subclass/NotTheSmoooze; RoguishArchetypes.json
> +					"type": "table",
same here

2022-02-01 00:32 UTC, CorrTerek commented on subclass/NotTheSmoooze; RoguishArchetypes.json
> +					"type": "table",
I'll get right on that.

2022-02-01 00:38 UTC, CorrTerek commented on subclass/NotTheSmoooze; RoguishArchetypes.json
> +					"type": "table",
Should be good now.

2022-02-05 19:26 UTC, TheGiddyLimit requested changes

2022-02-05 19:26 UTC, TheGiddyLimit commented on subclass/NotTheSmoooze; RoguishArchetypes.json
> +				"blowgun": true
needs to be `blowgun|phb`

2022-02-08 19:07 UTC, merged