Expanded Floran Spells
TheGiddyLimit/homebrew pull request #1249
Opened 2022-02-17 23:13 UTC by cadowtin

2022-02-18 00:22 UTC, revilowaldow requested changes

2022-02-18 00:22 UTC, revilowaldow commented on spell/Sonixerse; Expanded Floran Spells.json
> +	"siteVersion": "1.149.1",
```suggestion

```

2022-02-18 00:22 UTC, revilowaldow commented on spell/Sonixerse; Expanded Floran Spells.json
> +				"url": "https://www.gmbinder.com/share/-Mpx4PhPMBXmAN-i3P95",
```suggestion
				"url": "https://www.gmbinder.com/share/-Mpx4PhPMBXmAN-i3P95",
				"version": "Updated Thursday, 16 December 2021 16:13:34.315",

```

2022-02-18 00:22 UTC, revilowaldow commented on spell/Sonixerse; Expanded Floran Spells.json
> +				"poison and necrotic (blighted and fungal only)"
```suggestion
				{
					"immune": [
						"poison",
						"necrotic"
					],
					"cond": true,
					"note": "(blighted and fungal only)"
				}

```

2022-02-20 14:26 UTC, TheGiddyLimit approved these changes

2022-02-20 14:26 UTC, merged