Added Caravaneer
TheGiddyLimit/homebrew pull request #1258
Opened 2022-02-23 13:31 UTC by cadowtin

2022-02-24 16:25 UTC, cadowtin commented
it's very broken and I am very lost as to why

2022-02-24 20:28 UTC, revilowaldow requested changes

2022-02-24 20:28 UTC, revilowaldow commented on subclass/PosTavern; Artificer Specialist - Caravaneer.json
> +		"cha": 0,
```suggestion
		"cha": 0,
		"passive": null,
```

2022-02-24 20:28 UTC, revilowaldow commented on subclass/PosTavern; Artificer Specialist - Caravaneer.json
> +			"classSource": "TCE",
```suggestion
			"classSource": "TCE",
			"subclassShortName": "Caravaneer",
			"subclassSource": "AS:C",
```

2022-02-25 19:19 UTC, cadowtin commented
Okay it works now!

2022-02-25 19:19 UTC, cadowtin commented
Thank you for the help!

2022-02-27 16:37 UTC, TheGiddyLimit approved these changes

2022-02-27 16:38 UTC, merged