Cosmic Cleric Domain
TheGiddyLimit/homebrew pull request #1409
Opened 2022-07-27 21:12 UTC by JavaShipped

A mild homebrew of the Peace domain for a player.
- Changed Feature names.
- Amended Available subclass spells to fit the theme.

2022-07-28 16:05 UTC, revilowaldow requested changes

2022-07-28 16:05 UTC, revilowaldow commented on subclass/BeardedJB; Cosmic Cleric Domain.json
> +      "ShortName": "Cosmic",
```suggestion
```

2022-07-28 22:04 UTC, JavaShipped commented on subclass/BeardedJB; Cosmic Cleric Domain.json
> +      "ShortName": "Cosmic",
ah, my bad! That should be changed now!

2022-07-30 21:26 UTC, TheGiddyLimit approved these changes

2022-07-30 21:26 UTC, merged