Otherwordly patron: the toon
TheGiddyLimit/homebrew pull request #1430
Opened 2022-08-14 05:23 UTC by sammuns

Warlock subclass from the middle finger of vecna.

2022-08-14 15:30 UTC, TheGiddyLimit requested changes
Sources need fixing

2022-08-14 15:30 UTC, TheGiddyLimit commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
```suggestion
            "source": "MFOV:TT",
```

2022-08-14 15:30 UTC, TheGiddyLimit commented on subclass/thetoonwarlockpatron.json
> +                "Anvil on Head|Warlock||The Toon|WarlockToon|14"
```suggestion
                "The Toon|Warlock||The Toon|MFOV:TT|1",
                "Slaspstick|Warlock||The Toon|MFOV:TT|6",
                "Two-Dimensional|Warlock||The Toon|MFOV:TT|10",
                "Anvil on Head|Warlock||The Toon|MFOV:TT|14"

```

2022-08-14 15:30 UTC, TheGiddyLimit commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
etc. etc.

2022-08-16 15:21 UTC, Git-GoR requested changes
There are still references to the wrong source that need to be changed.

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
You need to change all the `WarlockToon` source references, as it does not exist. The only source in the meta is `MFOV:TT`:

```suggestion
            "source": "MFOV:TT",
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "subclassSource": "warlockToon",
Same thing:

```suggestion
            "subclassSource": "MFOV:TT",
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +                    "subclassFeature": "Expanded Spell List|Warlock||The Toon|WarlockToon|1|WarlockToon"
```suggestion
                    "subclassFeature": "Expanded Spell List|Warlock||The Toon|MFOV:TT|1|MFOV:TT"
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +                    "subclassFeature": "Big Pockets|Warlock||The Toon|WarlockToon|1|WarlockToon"
```suggestion
                    "subclassFeature": "Big Pockets|Warlock||The Toon|MFOV:TT|1|MFOV:TT"
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +                    "subclassFeature": "Zany Limbs|Warlock||The Toon|WarlockToon|1|WarlockToon"
```suggestion
                    "subclassFeature": "Zany Limbs|Warlock||The Toon|MFOV:TT|1|MFOV:TT"
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
```suggestion
            "source": "MFOV:TT",
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "subclassSource": "warlockToon",
```suggestion
            "subclassSource": "MFOV:TT",
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
```suggestion
            "source": "MFOV:TT",
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
```suggestion
            "source": "MFOV:TT",
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
```suggestion
            "source": "MFOV:TT",
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
```suggestion
            "source": "MFOV:TT",
```

2022-08-16 15:21 UTC, Git-GoR commented on subclass/thetoonwarlockpatron.json
> +            "source": "WarlockToon",
```suggestion
            "source": "MFOV:TT",
```

2022-08-28 15:03 UTC, TheGiddyLimit requested changes
Please see: https://github.com/TheGiddyLimit/homebrew/pull/1430/checks

Also, this file should be called e.g. `Mage Hand Press; The Toon Warlock Patron.json`

2024-06-23 21:22 UTC, TheGiddyLimit commented
superseded by #2154

2024-06-23 21:22 UTC, closed without merging