Add Conflux's SKeletons (no Pics)
TheGiddyLimit/homebrew pull request #1491
Opened 2022-09-27 17:53 UTC by cadowtin

2022-09-28 11:53 UTC, TheGiddyLimit requested changes

2022-09-28 11:53 UTC, TheGiddyLimit commented on creature/Conflux;Conflux's Skeletons.json
> +	"bookData": []
```suggestion
	]
```

2022-11-11 22:26 UTC, hakr14 requested changes

2022-11-11 22:26 UTC, hakr14 commented on creature/Conflux;Conflux's Skeletons.json
> +					],
The `resist` array expects specific values. In this case you probably want the following:
```json
"resist": [
    "piercing",
    "slashing"
]
```

2023-01-17 21:59 UTC, closed without merging