Update to DER (v5)
TheGiddyLimit/homebrew pull request #1528
Opened 2022-11-09 18:59 UTC by Mr-Batz

Updating Diverse Equestrian Races to now v5

2022-11-09 22:54 UTC, revilowaldow requested changes
Minor Issues

2022-11-09 22:54 UTC, revilowaldow commented on race/Mr Bat; Bats Diverse Equestrian Races.json
> +	"$schema": "../Diverse Equestrian Races.json",
```suggestion

```

2022-11-09 22:54 UTC, revilowaldow commented on race/Mr Bat; Bats Diverse Equestrian Races.json
> +				"type": "true"
```suggestion
				"walk": 30,
				"canHover": true
```

2022-11-13 23:46 UTC, TheGiddyLimit approved these changes

2022-11-13 23:46 UTC, merged