Add files via upload
TheGiddyLimit/homebrew pull request #1570
Opened 2022-12-14 10:27 UTC by badooga

Adds `badooga; Daedric Imports.json` and `badooga; Minecraft 5e.json`

2022-12-14 23:24 UTC, TheGiddyLimit requested changes
my bad; the schema got updates, but the builder can still output "bad" values. Fixed for next 5etools release

2022-12-14 23:24 UTC, TheGiddyLimit commented on creature/badooga; Daedric Imports.json
> +				"canHover": false
```suggestion
```

2022-12-14 23:29 UTC, TheGiddyLimit commented on creature/badooga; Daedric Imports.json
> +				},
```suggestion
				}
```

2022-12-14 23:45 UTC, revilowaldow commented on creature/badooga; Minecraft 5e.json
> +	"siteVersion": "1.171.0",
```suggestion

```

2022-12-15 00:13 UTC, TheGiddyLimit approved these changes

2022-12-15 00:14 UTC, merged