Create SeiTime;Amalgatrix.json
TheGiddyLimit/homebrew pull request #1670
Opened 2023-03-17 08:04 UTC by DMSei

Amalgatrix Species was created and converted by me, SeiTime.

2023-03-18 20:04 UTC, hakr14 commented on race/SeiTime;Amalgatrix.json
> +	"name": "Amalgatrix",
This and the following properties should be within an object in the `race` array. So it should look like:
```json
"race": [
    {
        "name": "Amalgamatrix",
        "source": "AMIX",
        ...
```

2023-03-18 21:38 UTC, hakr14 commented on race/SeiTime;Amalgatrix.json
> +	"fluff": {
The "fluff" object should be included in the above "race" object.

2023-03-19 01:27 UTC, hakr14 requested changes

2023-03-19 17:26 UTC, hakr14 requested changes

2023-03-19 17:26 UTC, hakr14 commented on race/SeiTime;Amalgatrix.json
> +		[
Delete

2023-03-19 17:26 UTC, hakr14 commented on race/SeiTime;Amalgatrix.json
> +	]
Delete

2023-03-19 17:26 UTC, hakr14 commented on race/SeiTime;Amalgatrix.json
> +			{
Delete

2023-03-19 17:26 UTC, hakr14 commented on race/SeiTime;Amalgatrix.json
> +				"authors": "Sei Time",
So this line is `"authors": ["Sei Time"],`

2023-03-19 17:28 UTC, hakr14 commented
In future you really should be using an IDE that can validate JSON, such as VSCode.

2023-03-19 17:52 UTC, DMSei commented
> In future you really should be using an IDE that can validate JSON, such as VSCode.

Every edit I've made and the original upload I have done in Notepad++, and then verified in Virtual Studio Code before submission. Only the second last edit/upload had errors in VSCode. This is my first time creating a race json. There is bound to be issues, or errors that need correcting. I apologize for my lack of experience in this matter.

2023-03-22 21:34 UTC, DMSei commented
I don't have any errors in VSCode anymore. Is this good and properly formatted for use now?

2023-03-26 17:09 UTC, TheGiddyLimit requested changes
Not quite; peek the "Checks" tab at the top of the PR: [https://github.com/TheGiddyLimit/homebrew/pull/1670/checks](https://github.com/TheGiddyLimit/homebrew/pull/1670/checks)

2023-03-27 10:19 UTC, DMSei commented
@TheGiddyLimit Thanks. I made some alterations to the file in order to get past the error I was experiencing. It is still saying there is an error when the check runs saying that AMIX is not in the _meta source. But it is. Do you know what it is I am doing wrong?

2023-03-27 22:38 UTC, TheGiddyLimit approved these changes

2023-03-27 22:38 UTC, merged