Add files via upload
TheGiddyLimit/homebrew pull request #1887
Opened 2023-10-21 22:40 UTC by JamesMcGowan123

After much toil and trouble, the early version of our witch class is finally here and available to you, our beloved patrons!! A lot of care and deliberation went into developing the class for Erika to use, and we’ve been so eager to share it with you all and hear what you think.

We have to stress that this is an early draft of the class mechanics—it hasn’t been thoroughly playtested (you’ve basically heard the extent of it on the podcast), so GMs should be fully aware of that before allowing it to be used in their games.

Because of this, we’ll be seeking feedback from the Patreon in a month or two, once people have had some time to play the class and test it out. We don’t expect feedback, but if you decide to try it out and are willing to share some thoughts, we’d love to hear from you, so keep an eye out!

Big thanks to everyone who helped us put this together, including designers Mazey Veselak, Brandes Stoddard, and Hannah Rose; layout artist Ruby Lavin; illustrators Corey Brickley, Tucker Donovan, and Taylor Moore; and original character illustrator Lorena Lammer.

2023-10-22 16:48 UTC, revilowaldow requested changes
Actually never mind there's loads more than I anticipated.
Everywhere you use  `WitchWBNSpells`, switch it for `WitchWBN`

2023-10-22 16:48 UTC, revilowaldow commented on class/Worlds Beyond Number; The Witch.json
> +				"Cackle|WitchWBNSpells",
```suggestion
				"Cackle|WitchWBN",
```

2023-10-22 16:48 UTC, revilowaldow commented on class/Worlds Beyond Number; The Witch.json
> +				"Witch's Grasp|WitchWBNSpells",
```suggestion
				"Witch's Grasp|WitchWBN",
```

2023-10-22 16:48 UTC, revilowaldow commented on class/Worlds Beyond Number; The Witch.json
> +				"Cleansing Crystal|WitchWBNSpells",
```suggestion
				"Breath of Belladonna|WitchWBN",
				"Cleansing Crystal|WitchWBN",
```

2023-10-22 21:57 UTC, revilowaldow commented on class/Worlds Beyond Number; The Witch.json
> +						"{@item Potion of resistance} (you decide the type of resistance it grants)}",
```suggestion
						"{@item Potion of resistance} (you decide the type of resistance it grants)",
```

2023-10-22 23:18 UTC, JamesMcGowan123 commented on class/Worlds Beyond Number; The Witch.json
> +						"{@item Potion of resistance} (you decide the type of resistance it grants)}",
I have deleted the }

2023-10-29 22:31 UTC, TheGiddyLimit approved these changes

2023-10-29 22:31 UTC, merged