Added Arcanum Worlds; Odyssey of the Dragonlords
TheGiddyLimit/homebrew pull request #1992
Opened 2024-02-04 17:47 UTC by shadowslasher410

I hope I'm doing this right... Anyway, all of the book except some of the appendices is there.

2024-02-07 13:06 UTC, TheGiddyLimit requested changes
couple things:

- please avoid making changes to `package-lock.json` (preferably amend your commit(s) to remove those changes; but reverting them is also fine)
- please don't shorten `json` sources; `ArcanumWorldsOdysseyoftheDragonlords` was an ideal name as-is. If that's too long, then `OdysseyoftheDragonlords` is also fine

2024-02-10 21:55 UTC, TheGiddyLimit requested changes
getting there, but the image dir is still named `OotD`; please rename it to match the JSON source also
(and presumably find-replace all the image paths)

2024-02-18 22:51 UTC, TheGiddyLimit approved these changes

2024-02-18 22:51 UTC, merged

2024-04-20 08:21 UTC, briavers commented
You good sir, Thank you