Chronicles of Eberron
TheGiddyLimit/homebrew pull request #2019
Opened 2024-02-25 05:12 UTC by BucketListMod

- Added Chronicles of Eberron (mechanics only)
- Updated/fixed Exploring Eberron

2024-02-25 21:03 UTC, TheGiddyLimit commented on collection/Keith Baker; Chronicles of Eberron.json
> +	"bookData": [],
```suggestion
```

2024-02-25 21:08 UTC, TheGiddyLimit requested changes
looks like this could use some local testing + fixing

2024-02-26 01:25 UTC, BucketListMod commented
> looks like this could use some local testing + fixing

I did local testing and fixing before committing the changes, worked fine on my device? Skimming through I found a few more small errors in ExE that I could fix and I could change the "psiactive" property from "special" to its own kind, but the pages function normally and all the mechanics work fine?

2024-02-27 20:24 UTC, TheGiddyLimit commented
apologies, I mean specifically running `npm run test:json` locally; it's failing some schema checks

2024-03-03 22:18 UTC, TheGiddyLimit commented
looks like you've now got some merge conflicts 🙈 you'll need to do a `git pull`

2024-03-03 23:13 UTC, BucketListMod commented
Would it be smarter/easier to just close this one and open a new one? 🤣

2024-03-03 23:21 UTC, closed without merging