Voxkrynn;vulpinesystems.json
TheGiddyLimit/homebrew pull request #2048
Opened 2024-03-15 09:21 UTC by VoxKrynn

2024-03-17 17:00 UTC, TheGiddyLimit requested changes
file should be moved to e.g. `creature/VoxKrynn; Vulpine Systems.json` (note the addition of spaces, too)

2024-03-17 22:17 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +				"color": "#490085"
```suggestion
				"color": "490085"
```

2024-03-17 22:21 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +				"url": "",
```suggestion
```

2024-03-17 22:21 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +				"convertedBy": [],
```suggestion
```

2024-03-17 22:40 UTC, TheGiddyLimit requested changes

2024-03-17 22:40 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +			"uniqueId": "1b04ebf4-2ac4-432c-9721-dd8b2ec5b637",
```suggestion
```

2024-03-17 22:40 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +			"uniqueId": "d6698f05-3463-419d-965e-99ab8e657c69",
```suggestion
```

2024-03-17 22:40 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +			"uniqueId": "a9f8fa42-bc66-460c-9dc7-5661c96091c6",
```suggestion
```

2024-03-17 22:40 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +			"uniqueId": "b60e91b5-92b3-47dc-ac7a-7608ef070ccf",
```suggestion
```

2024-03-17 22:40 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +			"uniqueId": "86145d67-e970-4c72-9daa-a09ff4e62d21",
```suggestion
```

2024-03-17 22:40 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +			"uniqueId": "eacb47de-5e95-4185-9937-0905a6468ea0",
```suggestion
```

2024-03-17 22:40 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +			"uniqueId": "7816c494-2568-408e-88db-34ff8b7f67d7",
```suggestion
```

2024-03-17 22:40 UTC, TheGiddyLimit commented on creature/VoxKrynn; Vulpine Systems.json
> +			"uniqueId": "75b36ff7-f31a-4152-8eef-cc9f76197d52",
```suggestion
```

2024-03-18 04:57 UTC, closed without merging

2024-03-18 12:18 UTC, TheGiddyLimit commented
@VoxKrynn apologies, I meant to follow up on this

do you no longer want the file added to the repo? It probably only needs a couple more minor fixes; I _think_ they're all from bugs in the homebrew builder (hopefully fixed for next release), hence my meddling

the `alignment` issues I thought I already fixed, which version of 5etools are you using? I.e. are you still on the old https://5etools-mirror-1.github.io ver..?

2024-03-19 14:14 UTC, VoxKrynn commented
Sorry I just don't really know what I am doing here, and I realized that I will have to keep doing this when I add more things to the homebrew. So I think it would just be easier for me to share it manually. For the version I am using I am unsure, it is just the standard version that you get when you just google it. Just looked before sending this, I am using 1.201.1 5eTools.

2024-03-19 15:04 UTC, TheGiddyLimit commented
fair enough, no worries