Some update of my work and some contribution
TheGiddyLimit/homebrew pull request #2208
Opened 2024-08-07 12:35 UTC by p4535992

Some update of my work 
Added Haste Knight: https://github.com/TheGiddyLimit/homebrew/pull/2002 
Update Alchemist from https://github.com/TheGiddyLimit/homebrew/pull/1906
Added Aviala Race from https://github.com/TheGiddyLimit/homebrew/pull/1686
Added collection from https://github.com/TheGiddyLimit/homebrew/pull/1618

2024-08-10 11:10 UTC, TheGiddyLimit requested changes
there's a font folder in the img repo; mind putting your font there instead? https://github.com/TheGiddyLimit/homebrew-img/tree/main/font

2024-08-10 11:57 UTC, p4535992 commented
Removed  the font file

2024-08-10 20:33 UTC, TheGiddyLimit approved these changes

2024-08-10 20:33 UTC, merged

2024-09-05 16:48 UTC, revilowaldow commented
@TheGiddyLimit think a lot of the PRs linked in the original message above can be closed