Create Bovenbrew; Bovenbrew Weapon Arts
TheGiddyLimit/homebrew pull request #2241
Opened 2024-09-04 01:31 UTC by Michiel-de-Ruyter

An alternative take on the BG3 weapon actions system meant to give weapon users more tactical options compared to their option-rich spellcaster party members. 

Also includes some weapon arts meant to work with exotic weapons that I will upload homebrew for later.

2024-09-04 18:42 UTC, hakr14 requested changes
Conditions require a page for whatever reason. & 2 other minor errors

2024-09-04 18:42 UTC, hakr14 commented on variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> +                "targetSchema": "1.0"
```suggestion
                "url": "http://bovenbrew.wikidot.com/"
```

2024-09-04 18:42 UTC, hakr14 commented on variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> +                "count": "666",
```suggestion
                "count": 666,
```

2024-09-04 18:42 UTC, hakr14 commented on variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> +			"source": "Bovenbrew Weapon Arts"
```suggestion
			"source": "Bovenbrew Weapon Arts",
                        "page": ""
```

2024-09-04 18:42 UTC, hakr14 commented on variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> +			"source": "Bovenbrew Weapon Arts"
```suggestion
			"source": "Bovenbrew Weapon Arts",
                        "page": ""
```

2024-09-04 18:42 UTC, hakr14 commented on variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> +			"source": "Bovenbrew Weapon Arts"
```suggestion
			"source": "Bovenbrew Weapon Arts",
                        "page": ""
```

2024-09-04 18:42 UTC, hakr14 commented on variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> +			"source": "Bovenbrew Weapon Arts"
```suggestion
			"source": "Bovenbrew Weapon Arts",
                        "page": ""
```

2024-09-04 18:42 UTC, hakr14 commented on variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> +			"source": "Bovenbrew Weapon Arts"
```suggestion
			"source": "Bovenbrew Weapon Arts",
                        "page": ""
```

2024-09-04 18:42 UTC, hakr14 commented on variantrule/Bovenbrew; Bovenbrew Weapon Arts.json
> +			"source": "Bovenbrew Weapon Arts"
```suggestion
			"source": "Bovenbrew Weapon Arts",
                        "page": ""
```

2024-09-04 19:45 UTC, Michiel-de-Ruyter commented
Fixed implemented, thanks

2024-09-08 22:40 UTC, TheGiddyLimit approved these changes

2024-09-08 22:40 UTC, merged

2024-09-08 22:41 UTC, TheGiddyLimit commented
will fix homebrew conditions(/diseases/statuses) requiring a page for next release